xcodeproj 'Food Journal.xcodeproj'
platform :ios, '5.0'

pod 'A2StoryboardSegueContext'
pod 'AFNetworking'
pod 'AZCoreRecord', :git => 'https://github.com/zwaldowski/AZCoreRecord.git', :branch => 'next'
pod 'BlocksKit'
pod 'DZProgressController'
pod 'MGImageUtilities', :git => 'https://github.com/a2/MGImageUtilities.git'
pod 'Reachability'
pod 'SSKeychain'
pod 'UIImage-Categories'
pod 'UIImage+PDF'
pod 'xmlrpc'